name: Deploy to OCI
on:
  push:
    branches: master

jobs:
  Deploy-to-OCI:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i
      - run: npm run prebuild
      - run: npm run build:typescript
      - run: npm prune --production
      - run: pwd
      - run: ls
      - name: SSH Remote Commands
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSHPRIV }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_PORT: ${{ secrets.PORT }}
          SOURCE: "build docs views node_modules package-lock.json sleepingSettings.yml package.json"
          TARGET: ${{ secrets.DEST }}
          SCRIPT_AFTER: |
            cd ${{ secrets.DEST }}
            sudo ../deploy.sh
